---
repo_url: https://github.com/qctrl/template
site_description: A good description is clear, short, and to the point. Describe the purpose of the project and what it does.
site_name: Template
site_url: https://qctrl.github.io/template
theme: qctrl
